language: go
go:
  - "1.11.x"

env:
  global:
    - secure: RF2RpZJghZ5RwrBG9fKdGIbEFn/jRLZFu+mdGXtB9emxYTqBOhEFND/5F2rwPKrBkVDcB7HJehUnkuAn7N6tJV5DqdbEaaAdOHmG3NN2tZsKmyiwyBk2YwuJivjV0C/0PZVBccNz8x2y7xUGXcgnH3eEl4/2fDbu6QlEv1J4mfM5C8AnaXDko7mqMXQEpo7ysbb7YdvM5mVHIrqt4BKgoKulPGKTtc2r9cTzJMP6PqChBfwdbVQELiIKSB7SVdKqq/tXwSp3s38V1chIraqbUHridz+FJ6ZbPL+GMQdqJEt7hR47+OQxBwIJ2TTDawapWaQ3YYA6cdqvdlix3kYpRqlqRcRG8WVkhEJQHKPXsU5zw3S+wAo0axsk9tfXPUT6chWbCzcmRCQ6QvJQYoGpTEQn3Ql4eSwVMz5beRf6aZuFXXNEgYumloSQeG6edJi0af6UWdoUJ1EQn6loxhN/UoIJbdUKtp8Pg/ItvmUiIMgiQQap0LgxkV07jRBdOxesY3ExkytynUlOWXOG6rNO6qZL3b7hpv63XAEMJflblBEvALMHE9AFyskJAwqf9QSMWBlZQH4ZcRhl39CQVpTVaSXHB6a27+5MdX/Zc+G+SBBc2bdufyq6QJ0bBvNqfZAAE4dcWrQTpVF49AqeHmFa88tEfjR0Jk7b5nWZb4BbzZw=

addons:
  apt:
    packages:
    - rpm

dist: trusty
sudo: false

script: env GO111MODULE=on go test ${gobuild_args} ./...

deploy:
  provider: script
  script: curl -sL https://git.io/goreleaser |GO111MODULE=on bash
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
